import type { Metadata } from "next";
import "@styles/globals.css";
import Navbarr from "@components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Navbarr />     
        {children}
      </body>
    </html>
  );
}
